### ISSUE TITLE
Blank output variable from SARRA-O

### ISSUE THREAD

**Issue by Stanley997** [SARRA-cropmodels/SARRA-O#1]
Hi team, I am having some issues with my simulation test. My output variables from the SARRA-O comes out blank (without any data). First of all, I converted my regional climate data (West Africa) from netcdf to geotiff format for daily timeseries of input variables from 1951 to 1965. I ran the simulations for West Africa (as defined in my research objective); however, my result comes out in form of a blank tiff file. I don't know what the problem could be. I have run some diagnostic tests with my input data, and they seem okay but I am still stuck and out of possible solutions.

**Comment by codename5281** [comment]
Hello @Stanley997,

Thanks for reaching out. I must admit SARRA-O is not very talkative when it comes to errors !

In this case, the first thing you may want to do would be to download a dataset has been shown to be fully usable with SARRA-O such as [this one published on Zenodo](https://zenodo.org/doi/10.5281/zenodo.11091602). First, give a test run with them to check that you are able to generate outputs, then have a look at its geotiffs under QGis next to your own dataset.

Ideally you'd want to check your own prepared data to see if the values are in the same order of magnitude of the example ones. If not, this could be caused by a discrepency in the units. 

Let me know !
Best,
J.

**Comment by Stanley997** [comment]
Hello J,

Once again, I truly appreciate your responses and making out time for me on my research. I have looked at the magnitude of the data and other dimensions in QGIS too, but I am still getting the same result. I want to know if there is any data across West Africa in order to compare with mine, as the one provided is for Niger. Find attached in the link [] #(https://1drv.ms/f/s!AreYejae9s2cjBtpMx73HGcYL8dM?e=g6MSXL)  a sample of my one-day temperature data over West Africa in comparison to the Niger data provided in the Github for your reference.



Thank you
Stanley.

**Comment by codename5281** [comment]
Hello again @Stanley997,

Thanks for sharing this info. From what i see there does not seem to be any issue with your temperature - did you compare the orders of magnitude of the other entry variables as well ? 

If yes, one thing you could do would be to set up a simulation run from the example files, but replace one of the example variables with your dataset. Like so you should be able to identify if there is one particular variable that is blocking the correct run.

Let me know,
J.

**Comment by Stanley997** [comment]
Hello J,

Thank you for your response. I have tried the above options too but to no avail. I think the reason is because the variable dates are different. While the example datasets are for the period of 1981, my datasets are for 1952 period. I have just updated other variables for your reference.

Thank you
Stanley.

**Comment by codename5281** [comment]
@Stanley997 ,

Could you prepare some data for 1981 just to run against reference data so we can check your historical data preparation method is ok ?

**Comment by Stanley997** [comment]
Hello J,

Good morning to you once again. 

I have tried the above, but I am still getting the same result. Below is the code I use to covert to geotiff in windows.

```
# Load necessary libraries
library(ncdf4)
library(raster)

# Specify the path to the NetCDF file containing multiple years of data
nc_file <- "C:\\Users\\User\\Downloads\\climate_database\\New climate data\\ETP\\pet_IPSL_ssp245_1951-1965.nc"
print(nc_file)

# Define the output directory
output_dir <- "C:\\Users\\User\\Desktop\\MSc Project\\mydata\\ETP"

# Function to convert NetCDF to daily GeoTIFF files
convert_nc_to_daily_tiff <- function(nc_file, output_dir) {
  # Load the NetCDF file
  nc_data <- brick(nc_file)
  
  # Get the time dimension from the NetCDF file
  nc <- nc_open(nc_file)
  time <- ncvar_get(nc, "time")
  time_units <- ncatt_get(nc, "time", "units")$value
  nc_close(nc)
  
  # Convert time units to Date format
  # Assuming time units are in 'days since YYYY-MM-DD'
  origin_date <- as.Date(substr(time_units, 12, 21))
  dates <- origin_date + time
  
  # Loop through each layer and save as a separate GeoTIFF file
  for (i in 1:nlayers(nc_data)) {
    # Extract the layer
    daily_data <- subset(nc_data, i)
    
    # Generate the date for the current layer
    date_str <- format(dates[i], "%Y_%m_%d")
    
    # Create the output file name
    output_file <- file.path(output_dir, paste0("ET0_", date_str, ".tiff"))
    
    # Save the raster as a TIFF file
    writeRaster(daily_data, output_file, format = "GTiff", overwrite = TRUE)
  }
}

# Convert the single NetCDF file into daily GeoTIFF files
convert_nc_to_daily_tiff(nc_file, output_dir)

```

**Comment by codename5281** [comment]
Hello @Stanley997 ,

Could you provide a link where to download one full year for all the necessary variables ? Like so i can have a look and tell you.

J.

**Comment by Stanley997** [comment]
hello J,

Do you mean the .tiff files or .nc files?

Stanley.

**Comment by codename5281** [comment]
.tiff files please

**Comment by Stanley997** [comment]
Hello again J,

Kindly find attached link [https://drive.google.com/drive/folders/1QcPG5Y96WCQqeMiEo9szOyqIQ2SJxCCO?usp=drive_link](url) to 2052 variables required for SARRA-O.

Thank you,
Stanley

**Comment by Stanley997** [comment]
Hello again J,

Kindly find attached link []#(https://drive.google.com/drive/folders/1QcPG5Y96WCQqeMiEo9szOyqIQ2SJxCCO?usp=drive_link) to 2052 variables required for SARRA-O.

Thank you
Stanley

**Comment by codename5281** [comment]
@Stanley997 ,

Could you provide a open link ? This one needs authentification.

**Comment by Stanley997** [comment]
Oh sorry..
Try this!

[]#(https://drive.google.com/drive/folders/1QcPG5Y96WCQqeMiEo9szOyqIQ2SJxCCO?usp=sharing)

**Comment by Stanley997** [comment]
Hello J,

Good morning. I hope you are good?. I am checking in to make sure you are able to access the datasets now.

Thank you.
Stanley.

**Comment by codename5281** [comment]
Hello @Stanley997 ,

Yes, i was able to download them. Be a bit patient though, i'm not full time on the customer support :)

**Comment by codename5281** [comment]
@Stanley997 ,

From you data, i tried to run a test simulation for 2052, and indeed there were only blank values on the outputs. The speed at which the computations seemed to be performed made me think about an issue with I/O. 

Then, i noticed your files have a `.tiff` extension, however it seems **the correct extension recognized by SARRA-O is `.tif`**. After renaming all your files, i launched again a simulation for Senegal for 2052 with some default parameters. Below is the yield result.

![image](https://github.com/SARRA-cropmodels/SARRA-O/assets/44723543/b6d2c4ba-20d5-4ccf-a4b4-92e1dc3c542f)

So i guess the error was there :)

Feel free to close the issue if i answered your question.
Best,
J.

**Comment by Stanley997** [comment]
@codename5281 

Wow.. I am well pleased to hear this. I am already renaming the files. Will get back to you as soon as posible.
Thank you so much for this development.

Best
Stanley

**Comment by Stanley997** [comment]
Hello @codename5281 
I just ran a simulation for the whole of west africa and got a result..
Thank you so much.

Best
Stanley.
